title: Hacking related blog
email: n/a
description: "This blog is about cybersecurity related stuff, such as Bug Bounty, Penetration Testing, CTFs, etc."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: spenkkkkk
github_username:  spenkk

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md

style: dark # dark (default) or light
footer: 'follow me on twitter twitter.com/spenkkkkk'

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
