title: "Arben Shala | Personal Blog"
email: n/a
description: ""
baseurl: ""
url: ""
twitter_username: arbennsh
github_username:  spenkk

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - categories.md
  - about.md

permalink: /:categories/:title/

style: dark
listen_for_clients_preferred_style: true
footer: ""
